sudo: required
cache: docker

language: python

services: 
  - docker

env:
  - R_VERSION=3.5.0 TIDYVERSE=0
  - R_VERSION=3.4.0 TIDYVERSE=0
  - R_VERSION=3.3.0 TIDYVERSE=0
  - R_VERSION=3.2.0 TIDYVERSE=0
  - R_VERSION=3.1.0 TIDYVERSE=0
  - R_VERSION=3.0.0 TIDYVERSE=0

  - R_VERSION=3.5.0 TIDYVERSE=1
  - R_VERSION=3.4.0 TIDYVERSE=1
  - R_VERSION=3.3.0 TIDYVERSE=1
  - R_VERSION=3.2.0 TIDYVERSE=1
  - R_VERSION=3.1.0 TIDYVERSE=1
  - R_VERSION=3.0.0 TIDYVERSE=1

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

script:
  - docker image build -t r-base:$R_VERSION --build-arg=R_VERSION=$R_VERSION --build-arg=TIDVERSE=$TIDYVERSE .
  - if [ $TIDYVERSE == 1 ] then; docker tag r-base:tidyverse-$R_VERSION mattpaletta/r-base:tidyverse-$R_VERSION; else docker tag r-base:$R_VERSION mattpaletta/r-base:$R_VERSION; fi
after_success:
  - if [ $TIDYVERSE == 1 ] then; docker push mattpaleta/r-base:tidyverse-$R_VERSION; else docker push mattpaletta/r-base:$R_VERSION; fi
