sudo: required
cache: docker

language: python

services: 
  - docker

env:
  - R_VERSION=3.5.0
  - R_VERSION=3.4.0
  - R_VERSION=3.3.0
  - R_VERSION=3.2.0
  - R_VERSION=3.1.0
  - R_VERSION=3.0.0
  - R_VERSION=2.9.0

before_install:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

script:
  - docker image build -t r-base:$R_VERSION --build-arg=R_VERSION=$R_VERSION .
  - docker tag r-base:$R_VERSION mattpaletta/r-base:$R_VERSION
after_success:
  - docker push mattpaletta/r-base:$R_VERSION
